version: '3.8'

services:
  vismaya:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vismaya-demandops
    ports:
      - "8501:8501"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-2}
      - ENVIRONMENT=production
      - DEBUG=false
      - PORT=8501
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-us.anthropic.claude-3-haiku-20240307-v1:0}
      - DEFAULT_BUDGET=${DEFAULT_BUDGET:-80}
      - BUDGET_WARNING_LIMIT=${BUDGET_WARNING_LIMIT:-80}
      - BUDGET_MAXIMUM_LIMIT=${BUDGET_MAXIMUM_LIMIT:-100}
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      # AWS credentials: Use environment variables in .env file (recommended)
      # Alternative: Mount AWS credentials directory (uncomment one line below)
      # - ${HOME:-~}/.aws:/home/appuser/.aws:ro  # Linux/Mac  
      # - ${USERPROFILE}/.aws:/home/appuser/.aws:ro  # Windows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s